# Basic
title: Keke Yezi
subtitle: 重剑无锋 大巧不工
welcome_message: <a href="https://kekeyezi.github.io" target="_blank"> 爱游戏 & 爱动漫 & 爱编码  & 马上当爸爸了 希望记录自己的编程生涯 </a>
description: 我是叶斌 (Keke) 就职国泰君安.
# creator: <a href="https://kekeyezi.github.io">@onevcat</a>

url: "https://kekeyezi.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: 我的简历, url: 'https://kekeyezi.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: https://github.com/kekeYezi
    mail: kekeyezi1992@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
